import { FoodRegister } from "./register/Foodregister";
import { RecipeRegister } from "./register/RecipeRegister";
import { PancakePlace } from "./blocks/PancakePlace";
import { Pancake } from "./blocks/Pancake";
import { BlockFoodRegister } from "./register/BlockFoodRegister";
new FoodRegister();
new RecipeRegister();
new PancakePlace();
new Pancake();
new BlockFoodRegister();